{% set version = "1.3" %}

{% set posix = 'm2-' if win else '' %}

package:
  name: r-fail
  version: {{ version|replace("-", "_") }}

source:
  fn: fail_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/fail_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/fail/fail_{{ version }}.tar.gz
  sha256: ede8aa2a9f2371aff5874cd030ac625adb35c33954835b54ab4abf7aeb34d56d

build:
  noarch: generic
  number: 1006

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-bbmisc
    - r-checkmate

  run:
    - r-base
    - r-bbmisc
    - r-checkmate

test:
  commands:
    - $R -e "library('fail')"  # [not win]
    - "\"%R%\" -e \"library('fail')\""  # [win]

about:
  home: https://github.com/mllg/fail
  license: BSD-3-Clause
  summary: More comfortable interface to work with R data or source files in a key-value fashion.
  license_family: BSD

  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/BSD_3_clause
    - LICENSE
extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - daler
