travis:
  secure:
    BINSTAR_TOKEN: oPpTxBxHq/WPJHz6gPT60ueoF952RFEMN1gZ56R1JA6lyoRPaeL/IYvopPb7J+kqXX3b3+QtvINPfXXl2kFbivOmP+2j21BHzjt9KDIzLO9WhLtGP6pSq0AHmLj/bFjqotRlvZ3/GLmzTboPZRGts/YmSPLes2MSsYd8kKdPWaUDXSACt4EflUNDifO7SaDSGhrJeGmRmcgopJJDmUYHqemzhG6V1amoGfRxGZTeWz5UrQYooN+iikhS8vU+Ws3dzCuSNx82amfz2HVa3KJNm+S9475dMLvXDBj/dQ1o90xNRFHqcoCqzQ/4an2DJpRk9zXN6am3j04yzqZfl7kAF1JAAiuJrg0sfoSvW1bAiUUitO6R9wy18LBcFcRIHoD53Z5wj7O4FrT2413NNEqxps20NAUBITJ2dN9q8BhzD1FC4Ez3a7bPSySV3yhwHdydyCtq3f55gkvEQQ8wbFFUZl/7mOSDWucK6yek/K+0fLHVuHm+As9bKI41bOTlmiIhjSJCRrUUtqTH+Yz0LBW4D9EQg12x0BevIoZzLwMQAwFTJu95lMeTpg1IxpecDxa2iFzgi97qy/7veBWSeUd5n5i1Dzs3WTsYjA1qn5nGBn0W37M/PVWOBp2/HenXmB5h6S3u1udQEwxx424o7TdRc5Dz0pdBOjjwckwRvIbYX1w=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
