appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: visGP/fej8F24T0G8s+HD1vIzTpl84qmPyv5GfJ1U+3J0XQMRRHjLkk4Tt/+bjyN5TMY8sWtkoxVig7zKU6pSE9n7cn4zg00ced0QGvvugTBOWZENg9QJQ49EmL4Gs/pjUWxcL1RrmY2818gl7SSLLsaYtQla3zNtjsKA4Qr1XC7Oc0IeFOA9DJweHit3v/eSka8m/+KZy8XbjmfWSs1nHqSALkIfLTjbiKQDYF4uv9TJSBRiDNi95obaVjUI9IAFp6XBIEWaDhy3EXusZmyxiut7AoMwJFsr25Bmg7dPuiidIlDw8i0MEFchTAuLfLDybYpAlHfP81tOyvtn0xgxHVH8zsj7/p+0RgrXzQGUVXrIu8qp3xTjqwMTq2gE9K/IYz5eLJN95IbwfMSP5KmZryx62g5HJu5tTzl9tPLEWK8528JI92R3YiB4A3TcciEm0KWb8uHwlIMkxLJaP0OkrIrZiY/dm8Zl0lQMgCQCE7J9lmtI93Y695sDG4H62/IQKYINSKhtzCSV3ypui2XgkwZeFW4fAL2vSj2dAMFf+vS8ZnSQNLbfUUoGdRDhmMm+z2ewhlRlZfPo7TZtwWAwsV1bebHBxQKhOPJbmqWxMCgWKaBS7j4QmnKgNwkyn8eY9CFBgxYvpcWnvx6hb8NfHwyIzraGMZus4oqw9WSaNM=}
bot:
  automerge: true
