travis:
  secure:
    BINSTAR_TOKEN: Qlgn+dlZJmUdhh099nlzsFYkJBsFWVYJXJF9yo6wD4qsS7P/yNOmxvTBZtQvDKOBxnXTT3mmDxr8b58yzvvkXYKItubxgyJIR40F541jOEdh5q+hzshcuQyDDycCr9pFtXVPuvY47GJrSvPyglYvBb7P6RdBnTSpq4Xde34+v3MvAJ45u1fffZY/uyYFkqimUGGa9hr7mhvAH0XT+YybCZTSvMNiqa/pEMyMURCRn5jQVsGJ+rTuQSMS1HMUvftm9D9Ebn6jLRiwcWc5GRuCPG+SxOBXzoa8yDEH51WZY+RVl7rKB3BJUyC4B1AEP8oPdeQCY+IjIcm9BAPnfQw5g70jHKbODBiKZao4jZrT6+UsDq+sGAbtRL14gLXoFF2jbyZNwlag4R7eVxbk7JZyS2UA48YHeY+IrJGLGEg1/q5U6WOSzawDZdrAqU0Rek+DGRiTnkDcRkBqV2Sn8pr2JXEsS6ZWf98l8OTD8Olm/gO0URURU5+Ds5RUDS1NhtztGPTvyqaUkh7LDp2zqZhp6azQWRpwovVfbN+MJnwvazRsSN1c7CaAVunkjHj6P+Lu4/UaVw1075h0BPxKCr2xnz2HhzlEYFTYYKkGma+LfxlZ9uVJz2uVo4hpRE3gUs/zt2mF+t+oeSNNIePtgJ1iXZYqTSoAc/e6xjnQuMlS3/s=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
