travis:
  secure:
    BINSTAR_TOKEN: qVc2H7GOmE+urKXPhuHPWESPjcSIT3Y/U9/5XoZNidZAJCaHOriplDyfHgaFC1OwHbPM1ut0Xs6V48YxWOGUmsCD7bi5xGgWqnRAWlOenh0wUduMw8Poowb68ZN1K9chnUt1jbKwwEOz4C82Wm847Ell3K6CprYaULy2R3W2nt5QG1w9GCe7RzEHOgh0E0xEtX9nNIQPayJzjG4ZEg1XfOM7X1kaCxTha54FZlw2KrEgGDTMZlkXDfLYh9U2J1nmW+ktIhqdTEdywkT+nAbFUjpdo79XYqT15MJuVZoItZG7Hswn3G4EAkMu18Qrk7zBQ/V4Fc4Pg/iTSphrS1kvehWcF51AjEnIjGb3CN+vHuY7AHTXR1bGpUDLpdp5XiJ5NEkWo4ozY0vCIrp0Nf2kdtHWGivgLQ+KUuC6laygL6N91jLTjpDI2Cv1i5abmNtwiooYQj4ky7Zh3DGi9Z07kqzsEzNxv61+RLCPMdUUK3PgCxfr5mGCVQIFZNs2QadaR3cdFxJwYMWoI1f6Xltfc+vZMgDupm6bp2pMNkA5oFn+kYAyghTxn1IhG5AYd2b9O9AU2TnFEbDI/a4AYMwf6MiHRGNJ7xlFom6GvtbNmmP5dUqX+229Z5VMA9+p6gi83zgpN5vBaGpkGP5pgP5wR9jQHKviwgnrvBVIm9CiP6c=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
