travis:
  secure:
    BINSTAR_TOKEN: vEpWfHjmnTp0zMBEV5Wx6LfM8R7T4jCdcIjXflYG18RFSFcSctTZlnCVnE+RL8WfyE8UeQxd7foi85bNIdo1+wsMGl+gjukmVt6Lifcr+orSQOQc+J/ymaJ0G3dcdU5cM+ExWhIjY3ikZ5SqvQj74pwjVocCiPQQzUgx2EA7UG9pWRITB/LS/kha6Y+URMNm3qWTh6F9KwnDT2bxV//BgzM5JWzjDVXu+DsTYV68KH8BPSXT1xhKDHJehfF8iQ0rOlcTqcFxUptoShFHtQry1lT+ZsqJ14t3WAKFzBZIR878tG26kMNSn9T03WX8aMIiKh20gW3cQdStivCZYkqOwk5k6hYhoXTkNXATxaHeObySlvptUM18UdSCMuD0zJWd611fmmfj8xJlxCflw83pqdxTKJSa0lpv2ffD1blULPO4Fyoq7+bg3yb7uW/kmLPjU69kZAnv+0p3ZTlVaJVojsUDSwtMqPl0ziAeYg4OBHa8G0UYqTUONU52YhyasZUwVciQPXNy9LbihzqCd04ysiaHqGSqopturyQJ8YbMmb1+aNrYAhHv6MO9jRFQ/f4/53tW0j9PDx1VlC5iH7Pr8hjD+Ktnfo17ERObuVze4ED8xHc+7ly/GbDLXgGbAdUHmrrvpKnTmLGbQEvJW0hmA9M3mvd6UWlsDOJpm7D8TxA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
